Integrate Mayhem
mayhemheroes/mdformat pull request #1
Opened 2022-05-26 00:53 UTC by ebell495

2022-07-23 23:39 UTC, xansec requested changes
Please make the requested changes.

2022-07-23 23:39 UTC, xansec commented on Mayhemfile
> +project: mdformat
Tests has been changed to testsuite. Please make this change in this file as well. You may also omit it entirely.

2022-07-24 03:04 UTC, ebell495 commented on Mayhemfile
> +project: mdformat
I've fixed this

2022-07-25 18:53 UTC, xansec approved these changes
LGTM!

2022-07-25 18:53 UTC, merged